### ISSUE TITLE
Supervisor wont work

### ISSUE THREAD

**Issue by chefchefkitchen** [balenalabs-incubator/balena-homeassistant#8]
Hello I tried to install supervisor on the balena dashboard by pressing the update supervisor button in the options then I restarted my pi went to the dasboard on the ip of my pi and the supervisor was not there.

Please help!

**Comment by chrisys** [comment]
I think there's some confusion here between the balena supervisor and this home assistant project. I'd recommend posting on the balena forums at https://forums.balena.io if there are any further questions like this, it would get a quicker response :)

Closing
